---
grails:
    profile: web
    codegen:
        defaultPackage: crm
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html: 
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal: 
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            internalMaxFileSize: 150000
            maxFileSize: 99999999
            maxRequestSize: 99999999
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: ISO-8859-1
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
hibernate:
    cache:
        queries: false
---
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
    username: postgres
    password: postgres

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:postgresql://localhost:5432/crm_dev
            logSql: true
    test:
        dataSource:
            dbCreate: create-drop
            url: jdbc:postgresql://crmtestdb.c4ivuzc6wh7s.sa-east-1.rds.amazonaws.com:5432/
            logSql: true
    production:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://crmtestdb.c4ivuzc6wh7s.sa-east-1.rds.amazonaws.com:5432/
            logSql: true
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
logging:
    config: 'build/resources/main/logback.groovy'
crm:
    upload:
        image:
            partner: uploads/partner
            property: uploads/property
        template:
            report: uploads/template/report
        document:
            concession: uploads/document/concession
    application:
       path: C:/Users/claus/Documents/TRABAJO/inmo/cb_rep/trunk/CRM
web:
    image:
        partner: img/crm/partner
        property: img/crm/property